export const columns = [
  {
    title: '序号',
    dataIndex: 'firstIndex',
    editable: false,
  },
  {
    title: '属性',
    dataIndex: 'firstProps',
    editable: false,
  },
  {
    title: 'P',
    dataIndex: 'firstP',
    editable: true,
  },
  {
    title: 'I',
    dataIndex: 'firstI',
    editable: true,
  },
  {
    title: 'D',
    dataIndex: 'firstD',
    editable: true,
  },
  {
    title: '序号',
    dataIndex: 'secondIndex',
    editable: false,
  },
  {
    title: '属性',
    dataIndex: 'secondProps',
    editable: false,
  },
  {
    title: 'P',
    dataIndex: 'secondP',
    editable: true,
  },
  {
    title: 'I',
    dataIndex: 'secondI',
    editable: true,
  },
  {
    title: 'D',
    dataIndex: 'secondD',
    editable: true,
  },
  {
    title: '序号',
    dataIndex: 'thirdIndex',
    editable: false,
  },
  {
    title: '属性',
    dataIndex: 'thirdProps',
    editable: false,
  },
  {
    title: 'P',
    dataIndex: 'thirdP',
    editable: true,
  },
  {
    title: 'I',
    dataIndex: 'thirdI',
    editable: true,
  },
  {
    title: 'D',
    dataIndex: 'thirdD',
    editable: true,
  }
]


export const defaultDataSource = [
  {
    key: 'row-1',
    firstIndex: 1,
    firstProps: 'Rol 速率',
    firstP: 0,
    firstI: 0,
    firstD: 0,
    secondIndex: 7,
    secondProps: '高度速率',
    secondP: 0,
    secondI: 0,
    secondD: 0,
    thirdIndex: 13,
    thirdProps: 'PID13',
    thirdP: 0,
    thirdI: 0,
    thirdD: 0,
  },
  {
    key: 'row-2',
    firstIndex: 2,
    firstProps: 'PIT 速率',
    firstP: 0,
    firstI: 0,
    firstD: 0,
    secondIndex: 8,
    secondProps: '高度保持',
    secondP: 0,
    secondI: 0,
    secondD: 0,
    thirdIndex: 14,
    thirdProps: 'PID14',
    thirdP: 0,
    thirdI: 0,
    thirdD: 0,
  },
  {
    key: 'row-3',
    firstIndex: 3,
    firstProps: 'YAW 速率',
    firstP: 0,
    firstI: 0,
    firstD: 0,
    secondIndex: 9,
    secondProps: '位置速率',
    secondP: 0,
    secondI: 0,
    secondD: 0,
    thirdIndex: 15,
    thirdProps: 'PID15',
    thirdP: 0,
    thirdI: 0,
    thirdD: 0,
  },
  {
    key: 'row-4',
    firstIndex: 4,
    firstProps: '自稳 ROL',
    firstP: 0,
    firstI: 0,
    firstD: 0,
    secondIndex: 10,
    secondProps: '位置保持',
    secondP: 0,
    secondI: 0,
    secondD: 0,
    thirdIndex: 16,
    thirdProps: 'PID16',
    thirdP: 0,
    thirdI: 0,
    thirdD: 0,
  },
  {
    key: 'row-5',
    firstIndex: 5,
    firstProps: '自稳 PIT',
    firstP: 0,
    firstI: 0,
    firstD: 0,
    secondIndex: 11,
    secondProps: 'PID11',
    secondP: 0,
    secondI: 0,
    secondD: 0,
    thirdIndex: 17,
    thirdProps: 'PID17',
    thirdP: 0,
    thirdI: 0,
    thirdD: 0,
  },
  {
    key: 'row-6',
    firstIndex: 6,
    firstProps: '自稳 YAW',
    firstP: 0,
    firstI: 0,
    firstD: 0,
    secondIndex: 12,
    secondProps: 'PID12',
    secondP: 0,
    secondI: 0,
    secondD: 0,
    thirdIndex: 18,
    thirdProps: 'PID18',
    thirdP: 0,
    thirdI: 0,
    thirdD: 0,
  },
]
